# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to master

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "0 7 * * 1,3,5"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build
        env:
          CLIENT_USERNAME: ${{ secrets.CLIENT_USERNAME }}
          CLIENT_PASSWORD: ${{ secrets.CLIENT_PASSWORD }}
          CLIENT_POST_USERNAME: ${{ secrets.CLIENT_POST_USERNAME }}
          CLIENT_POST_PASSWORD: ${{ secrets.CLIENT_POST_PASSWORD }}
          GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
